name: Build DPT Android

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_VERSION: r25c
      ANDROID_API_LEVEL: 21

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential unzip wget

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
          unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux.zip -d $HOME/android-ndk
          echo "$HOME/android-ndk/android-ndk-${ANDROID_NDK_VERSION}" >> $GITHUB_PATH

      - name: Set environment variables
        run: |
          echo "ANDROID_NDK=$HOME/android-ndk/android-ndk-${ANDROID_NDK_VERSION}" >> $GITHUB_ENV
          echo "PATH=$ANDROID_NDK:$PATH" >> $GITHUB_ENV

      - name: Create build directories
        run: |
          mkdir -p build/armeabi-v7a
          mkdir -p build/arm64-v8a

      - name: Build armeabi-v7a
        run: |
          cmake -S shell/src/main/cpp \
                -B build/armeabi-v7a \
                -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=armeabi-v7a \
                -DANDROID_PLATFORM=android-${ANDROID_API_LEVEL} \
                -DCMAKE_BUILD_TYPE=Release
          cmake --build build/armeabi-v7a -j$(nproc)

      - name: Build arm64-v8a
        run: |
          cmake -S shell/src/main/cpp \
                -B build/arm64-v8a \
                -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-${ANDROID_API_LEVEL} \
                -DCMAKE_BUILD_TYPE=Release
          cmake --build build/arm64-v8a -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dpt-libs
          path: |
            build/armeabi-v7a/libdpt.so
            build/arm64-v8a/libdpt.so
